version: '3.8'

services:
  # --- SERVICE 1: DATABASE ---
  db:
    build: .
    container_name: my_postgres_vector
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}         # Lấy từ .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Lấy từ .env
      POSTGRES_DB: ${POSTGRES_DB}             # Lấy từ .env
    ports:
      - "5432:5432"
    volumes:
      - vnexpress_data_new:/var/lib/postgresql/data

  # --- SERVICE 2: PGADMIN ---
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}       # Lấy từ .env
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD} # Lấy từ .env
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  vnexpress_data_new:
  pgadmin_data:
